name = "gRPCClient2"
uuid = "b7a07a73-68ea-4538-9481-8488798afd91"
version = "0.1.1"
authors = ["Carroll Vance <cs.vance@icloud.com>"]

[sources]
ProtoBuf = {url = "https://github.com/csvance/ProtoBuf.jl", rev="external-service-support"}

[deps]
FileWatching = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"
LibCURL = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
ProtoBuf = "3349acd9-ac6a-5e09-bcdb-63829b23a429"

[compat]
FileWatching = ">= 1.10.10"
LibCURL = "0.6.4"
PrecompileTools = "1.3.3"
ProtoBuf = "1.2.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
